<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>otp_viaSMS</name>
   <tag></tag>
   <elementGuidId>4ab5ad38-9f13-40ba-90f1-524f8f79a1b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[data-testid='channel-sms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[data-testid='channel-sms']</value>
      <webElementGuid>ced0ded3-c712-44f3-8a0e-979835e4c1db</webElementGuid>
   </webElementProperties>
</WebElementEntity>
