<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_verificationCode_Input6</name>
   <tag></tag>
   <elementGuidId>4fc3a6cf-c6fc-4e80-b5b3-d5e2bf0763f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>89f71ae0-f957-432f-b23a-84ea250ce510</webElementGuid>
   </webElementProperties>
</WebElementEntity>
