<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_password</name>
   <tag></tag>
   <elementGuidId>c8fa0771-ac08-41b7-b293-155fe004f4f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[data-testid='input-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[data-testid='input-password']</value>
      <webElementGuid>be08c05b-7fd4-42a0-bc61-09a1403e51fc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
